# Generated by Django 5.0.7 on 2024-07-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('address', models.CharField()),
                ('name', models.CharField()),
                ('num_of_vehicles', models.IntegerField()),
            ],
        ),
    ]
