# Generated by Django 5.0.7 on 2024-07-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField()),
                ('completed', models.BooleanField(default=False)),
                ('place_of_service', models.CharField()),
                ('notes', models.TextField()),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_record', to='car_app.car')),
            ],
        ),
    ]
