# Generated by Django 5.0.7 on 2024-07-26 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine_app', '0001_initial'),
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=55)),
                ('model', models.CharField(max_length=55)),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
                ('year', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4)])),
                ('number_of_tires', models.IntegerField(validators=[django.core.validators.MinValueValidator(4)])),
                ('engine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engine_app.engine')),
                ('owners', models.ManyToManyField(related_name='car', to='owner_app.owner')),
            ],
        ),
    ]
